サインアップ機能開発
gogokoheiji/blog-system-725 pull request #1
Opened 2018-09-12 23:25 UTC by gogokoheiji

初プルリクエストです、お疲れ様です。
レビューをお願いします。

下記機能追加しました。
1.画面からパラメーターを受け取る
2.入力チェックを行う
3.DBに登録（clientテーブル、blogテーブル）
4.登録完了メールをユーザーと管理者に送信

以上、よろしくお願いします。

2018-09-14 09:05 UTC, halzion requested changes
ソースコードのレビューを行いました。
ひとまずsignup.phpの気づいた点をコメントしましたので修正をお願いします。

2018-09-14 09:05 UTC, halzion commented on app/models/client/signup.php
> +session_start();
今回のマッピング機構では、どのPHPプログラムも必ずindex.phpを通ってくるようになります。
session_start()は、index.phpで行っていますのでここでは不要です。

2018-09-14 09:05 UTC, halzion commented on app/models/client/signup.php
>  if ($_SERVER['REQUEST_METHOD'] != 'POST') {
講座のサンプルではこのような判定方法を行っていましたが、
否定比較は少々分かりづらいため、今後は以下のようにしていきましょう。
if ($_SERVER['REQUEST_METHOD'] == 'GET') {

2018-09-14 09:05 UTC, halzion commented on app/models/client/signup.php
>  	$pdo = connectDb();
connectDb()は、index.phpで共通で行うようにしましょう。

2018-09-14 09:05 UTC, halzion commented on app/models/client/signup.php
>  		unset($pdo);
unset($pdo)も、index.phpで行うようにしましょう。

2018-09-15 03:21 UTC, gogokoheiji commented
レピューありがとうございました。
ご指摘いただいた下記内容を修正しました。
・セッション開始、DB接続、DB切断をapp/index.phpへ移行
・client/signup.phpのリクエスト判定の変更

以上、サイレビューお願いします。

2018-09-16 09:52 UTC, halzion commented
CSRF対策が実装されていないようなので、こちらも実装しておきましょう。

2018-10-02 23:44 UTC, gogokoheiji commented
CSRF対策を共通関数に実装しsignup.phpにて実行しました。
レビューをよろしくお願いします。

2018-10-03 23:51 UTC, halzion commented
CSRFチェックの実装について、
トークンのhiddenタグの調整が出来ていないようですので
こちらもご確認をお願いします。

2018-10-15 00:07 UTC, gogokoheiji commented
お疲れ様です。ご確認ありがとうございます。
hiddenの調整が完了しました。
ご確認をよろしくお願いします。

2018-10-16 06:40 UTC, merged